window.NK_DATA = {
  office: {
    agentName: 'Neena Kalra',
    brokerage: 'NEENA K HOMES | Samson Properties',
    license: '#0225221074',
    phone: '(571) 277-2336',
    phoneHref: 'tel:5712772336',
    email: 'realtor.neena.kalra@gmail.com',
    emailHref: 'mailto:realtor.neena.kalra@gmail.com'
  },
  listings: [
    {
      slug: '23957-nightsong-ct-aldie-va-20105',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'featured', 'luxury', 'loudoun'],
      price: 1385000,
      beds: 5,
      baths: 4.5,
      sqft: 4200,
      acres: 0.5,
      type: 'Single Family',
      yearBuilt: 2005,
      garage: '2 Car Attached',
      hoa: 175,
      heating: 'Forced Air / Gas',
      cooling: 'Central A/C',
      schoolDistrict: 'LCPS',
      mls: 'VALO2078456',
      address: '23957 Nightsong Ct',
      city: 'Aldie',
      state: 'VA',
      zip: '20105',
      county: 'Loudoun County',
      neighborhoodSlug: 'aldie',
      heroImage: 'images/listing1.jpg',
      gallery: ['images/listing1.jpg', 'images/listing3.jpg', 'images/listing8.jpg'],
      description: 'Five-bedroom colonial with a walk-out basement, landscaped yard, and the room count luxury buyers expect in western Loudoun.',
      summary: [
        'Welcome to this stunning five-bedroom colonial in Aldie with a grand two-story foyer, hardwood floors across the main level, and a gourmet kitchen centered around an oversized island for everyday living and entertaining.',
        'The main floor balances formal spaces with practical ones: dining room, family room with fireplace, and a bright study that works well for remote work or multigenerational flexibility.',
        'Downstairs, the finished walk-out basement adds a recreation room, media zone, wet bar, and guest suite. Outside, the paver patio and mature landscaping make the backyard feel finished rather than builder-basic.'
      ],
      highlights: ['Walk-out basement with wet bar', 'Paver patio and landscaped yard', 'Dedicated study for remote work', 'Luxury owner suite with dual walk-ins'],
      taxesMonthly: 1050,
      insuranceMonthly: 325,
      mapQuery: '23957 Nightsong Ct, Aldie, VA 20105'
    },
    {
      slug: '14000-grumble-jones-ct-b-centreville-va-20121',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'featured', 'fairfax'],
      price: 455000,
      beds: 4,
      baths: 3,
      sqft: 3600,
      acres: 0.08,
      type: 'Townhouse',
      yearBuilt: 1998,
      garage: '1 Car Attached',
      hoa: 130,
      heating: 'Forced Air / Electric',
      cooling: 'Central A/C',
      schoolDistrict: 'FCPS',
      mls: 'VAFX2210945',
      address: '14000 Grumble Jones Ct #B',
      city: 'Centreville',
      state: 'VA',
      zip: '20121',
      county: 'Fairfax County',
      neighborhoodSlug: 'centreville',
      heroImage: 'images/listing2.jpg',
      gallery: ['images/listing2.jpg', 'images/listing4.jpg', 'images/listing6.jpg'],
      description: 'Spacious Centreville townhouse with strong commuter access, flexible living levels, and the value proposition buyers still search for in Fairfax County.',
      summary: [
        'This Centreville townhouse offers the square footage and room count buyers want without pushing into detached-home pricing. The layout is practical, bright, and easy to furnish.',
        'The kitchen opens into the main entertaining level, while upper-level bedrooms and lower-level flex space give the home enough separation for hybrid work and family routines.',
        'For buyers prioritizing value and access to I-66, Route 28, and shopping, this is the kind of home that keeps Centreville on shortlists.'
      ],
      highlights: ['Commuter-friendly Centreville location', 'Three finished levels', 'Flexible lower-level living space', 'Fairfax County value play'],
      taxesMonthly: 420,
      insuranceMonthly: 115,
      mapQuery: '14000 Grumble Jones Ct #B, Centreville, VA 20121'
    },
    {
      slug: '23684-evermont-trace-dr-ashburn-va-20148',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'loudoun'],
      price: 1180000,
      beds: 4,
      baths: 3,
      sqft: 3100,
      acres: 0.18,
      type: 'Single Family',
      yearBuilt: 2018,
      garage: '2 Car Attached',
      hoa: 165,
      heating: 'Forced Air / Gas',
      cooling: 'Central A/C',
      schoolDistrict: 'LCPS',
      mls: 'VALO2080034',
      address: '23684 Evermont Trace Dr',
      city: 'Ashburn',
      state: 'VA',
      zip: '20148',
      county: 'Loudoun County',
      neighborhoodSlug: 'ashburn',
      heroImage: 'images/listing3.jpg',
      gallery: ['images/listing3.jpg', 'images/listing1.jpg', 'images/listing7.jpg'],
      description: 'Modern Ashburn home with recent construction, clean finishes, and a layout designed for buyers who want turnkey living near Loudoun amenities.',
      summary: [
        'A newer-build Ashburn property with the clean lines, open floor plan, and updated systems buyers want when they are trying to avoid a heavy post-closing project list.',
        'The main living spaces flow naturally for entertaining, while the bedroom layout gives the home a comfortable everyday rhythm for families or frequent guests.',
        'Being in Ashburn keeps this home close to top schools, retail, and commuter routes, which is exactly why well-priced inventory here moves fast.'
      ],
      highlights: ['Newer construction feel', 'Open-concept main level', 'Strong Ashburn demand pocket', 'Close to retail and commuter routes'],
      taxesMonthly: 900,
      insuranceMonthly: 285,
      mapQuery: '23684 Evermont Trace Dr, Ashburn, VA 20148'
    },
    {
      slug: '25120-neptune-ter-chantilly-va-20152',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'featured', 'loudoun'],
      price: 600000,
      beds: 5,
      baths: 5,
      sqft: 4800,
      acres: 0.1,
      type: 'Townhouse',
      yearBuilt: 2012,
      garage: '2 Car Attached',
      hoa: 145,
      heating: 'Forced Air / Gas',
      cooling: 'Central A/C',
      schoolDistrict: 'LCPS',
      mls: 'VALO2079940',
      address: '25120 Neptune Ter',
      city: 'Chantilly',
      state: 'VA',
      zip: '20152',
      county: 'Loudoun County',
      neighborhoodSlug: 'chantilly',
      heroImage: 'images/listing4.jpg',
      gallery: ['images/listing4.jpg', 'images/listing2.jpg', 'images/listing8.jpg'],
      description: 'Large Chantilly property with flexible bedroom count and a strong balance of square footage, access, and neighborhood amenities.',
      summary: [
        'This Chantilly home stands out on usable space. Multiple finished levels, generous room sizes, and enough bathrooms to keep mornings from turning into gridlock make it practical for larger households.',
        'The layout can support a dedicated office, guest room, fitness area, or playroom without asking buyers to compromise their core living spaces.',
        'For buyers trying to stay close to Dulles Corridor employment while keeping a suburban neighborhood feel, this is a strong fit.'
      ],
      highlights: ['Large finished square footage', 'Flexible bedroom usage', 'Good access to Dulles corridor', 'Amenity-rich neighborhood'],
      taxesMonthly: 560,
      insuranceMonthly: 140,
      mapQuery: '25120 Neptune Ter, Chantilly, VA 20152'
    },
    {
      slug: '3738-freehill-ln-fairfax-va-22033',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'luxury', 'fairfax'],
      price: 985000,
      beds: 6,
      baths: 5,
      sqft: 5500,
      acres: 0.23,
      type: 'Single Family',
      yearBuilt: 2004,
      garage: '2 Car Attached',
      hoa: 120,
      heating: 'Forced Air / Gas',
      cooling: 'Central A/C',
      schoolDistrict: 'FCPS',
      mls: 'VAFX2211088',
      address: '3738 Freehill Ln',
      city: 'Fairfax',
      state: 'VA',
      zip: '22033',
      county: 'Fairfax County',
      neighborhoodSlug: 'fairfax',
      heroImage: 'images/listing5.jpg',
      gallery: ['images/listing5.jpg', 'images/listing7.jpg', 'images/listing6.jpg'],
      description: 'Fairfax luxury home with six bedrooms, substantial finished space, and a floor plan that works for multigenerational living.',
      summary: [
        'This Fairfax property offers scale: six bedrooms, multiple gathering areas, and the kind of finished lower level that buyers often try to add later at significant cost.',
        'The home reads as established and substantial, with enough room to support extended family, guests, or multiple work-from-home setups.',
        'Its Fairfax location also gives buyers access to a mature community fabric with schools, shopping, and transportation already in place.'
      ],
      highlights: ['Six-bedroom floor plan', 'Large finished basement', 'Established Fairfax setting', 'Multigenerational flexibility'],
      taxesMonthly: 760,
      insuranceMonthly: 240,
      mapQuery: '3738 Freehill Ln, Fairfax, VA 22033'
    },
    {
      slug: '3909-pender-spring-dr-fairfax-va-22033',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'fairfax'],
      price: 1200000,
      beds: 4,
      baths: 3,
      sqft: 3400,
      acres: 0.2,
      type: 'Single Family',
      yearBuilt: 2007,
      garage: '2 Car Attached',
      hoa: 110,
      heating: 'Forced Air / Gas',
      cooling: 'Central A/C',
      schoolDistrict: 'FCPS',
      mls: 'VAFX2208042',
      address: '3909 Pender Spring Dr',
      city: 'Fairfax',
      state: 'VA',
      zip: '22033',
      county: 'Fairfax County',
      neighborhoodSlug: 'fairfax',
      heroImage: 'images/listing6.jpg',
      gallery: ['images/listing6.jpg', 'images/listing5.jpg', 'images/listing3.jpg'],
      description: 'Recently sold Fairfax home included here as proof of execution, not just inventory.',
      summary: [
        'This recently sold property gives buyers and sellers context for what strong presentation and pricing can do in Fairfax County.',
        'The appeal came from condition, location, and a balanced four-bedroom layout that fits broad demand rather than a niche profile.',
        'Including sold examples on the site is useful because it shows track record, not just what happens to be active today.'
      ],
      highlights: ['Recently sold proof point', 'Strong Fairfax demand story', 'Balanced family-friendly layout', 'Useful comparable for sellers'],
      taxesMonthly: 980,
      insuranceMonthly: 300,
      mapQuery: '3909 Pender Spring Dr, Fairfax, VA 22033'
    },
    {
      slug: '42231-frontier-spring-dr-chantilly-va-20152',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'luxury', 'loudoun'],
      price: 966000,
      beds: 5,
      baths: 4,
      sqft: 5200,
      acres: 0.19,
      type: 'Single Family',
      yearBuilt: 2011,
      garage: '2 Car Attached',
      hoa: 155,
      heating: 'Forced Air / Gas',
      cooling: 'Central A/C',
      schoolDistrict: 'LCPS',
      mls: 'VALO2080102',
      address: '42231 Frontier Spring Dr',
      city: 'Chantilly',
      state: 'VA',
      zip: '20152',
      county: 'Loudoun County',
      neighborhoodSlug: 'south-riding',
      heroImage: 'images/listing7.jpg',
      gallery: ['images/listing7.jpg', 'images/listing5.jpg', 'images/listing1.jpg'],
      description: 'South Riding area home with luxury scale, polished finishes, and room for entertaining indoors and out.',
      summary: [
        'This Chantilly address sits in the Loudoun side of the market where buyers often want both square footage and access to community amenities.',
        'The interior is set up for practical daily use, but it is also the kind of home that can host without feeling strained.',
        'It works especially well for buyers targeting South Riding or nearby communities who want a step-up property without jumping to estate-level pricing.'
      ],
      highlights: ['South Riding area demand', 'Large entertaining footprint', 'Strong Loudoun school draw', 'Luxury feel without estate pricing'],
      taxesMonthly: 735,
      insuranceMonthly: 230,
      mapQuery: '42231 Frontier Spring Dr, Chantilly, VA 20152'
    },
    {
      slug: '42778-ravenglass-dr-ashburn-va-20148',
      status: 'Closed',
      statusStyle: 'sold',
      tags: ['sold', 'featured', 'luxury', 'loudoun'],
      price: 1130000,
      beds: 4,
      baths: 4,
      sqft: 3900,
      acres: 0.16,
      type: 'Single Family',
      yearBuilt: 2016,
      garage: '2 Car Attached',
      hoa: 170,
      heating: 'Forced Air / Gas',
      cooling: 'Central A/C',
      schoolDistrict: 'LCPS',
      mls: 'VALO2080453',
      address: '42778 Ravenglass Dr',
      city: 'Ashburn',
      state: 'VA',
      zip: '20148',
      county: 'Loudoun County',
      neighborhoodSlug: 'broadlands',
      heroImage: 'images/listing8.jpg',
      gallery: ['images/listing8.jpg', 'images/listing3.jpg', 'images/listing4.jpg'],
      description: 'Ashburn-area luxury listing with updated finishes, manageable lot size, and the polished feel move-up buyers want.',
      summary: [
        'A refined Ashburn-area home with a crisp finish palette, comfortable scale, and enough separation between public and private spaces to make the layout work well day to day.',
        'This property is appealing for buyers who want a premium location and upgraded feel without taking on an oversized lot or a full custom-home maintenance profile.',
        'Its position near Broadlands and western Ashburn amenities makes it a strong option for buyers comparing multiple Loudoun communities.'
      ],
      highlights: ['Move-up luxury option', 'Updated and polished interiors', 'Convenient Ashburn location', 'Strong fit for Broadlands buyers'],
      taxesMonthly: 860,
      insuranceMonthly: 270,
      mapQuery: '42778 Ravenglass Dr, Ashburn, VA 20148'
    }
  ],
  neighborhoods: [
    {
      slug: 'ashburn',
      name: 'Ashburn',
      county: 'Loudoun County',
      image: 'images/ashburn.jpg',
      medianPrice: '$750K',
      schoolScore: '9/10',
      commute: '35 min',
      overview: 'Ashburn is the center of Loudoun County convenience: strong schools, a steady stream of newer housing, major retail, and access to the Dulles tech corridor.',
      lifestyle: 'Buyers come here for neighborhood amenities, parks, youth sports, and proximity to everything from One Loudoun to Silver Line access.',
      housing: 'Expect a broad range from condos and townhomes to move-up single-family homes in highly planned communities.',
      schools: ['Top Loudoun County public school draw', 'Strong extracurricular depth', 'Family-oriented neighborhoods around school clusters'],
      commuteNotes: ['Access to Route 7, Route 28, and the Greenway', 'Useful for Dulles corridor and Reston commuters', 'Metro access expands options'],
      highlights: ['Master-planned communities', 'Retail and dining depth', 'Consistent buyer demand']
    },
    {
      slug: 'chantilly',
      name: 'Chantilly',
      county: 'Fairfax and Loudoun Counties',
      image: 'images/brambleton.jpg',
      medianPrice: '$680K',
      schoolScore: '8/10',
      commute: '30 min',
      overview: 'Chantilly sits at a practical crossroads for buyers who want commuter access, school options, and a wide range of home styles.',
      lifestyle: 'The area blends established neighborhoods with newer enclaves, major shopping corridors, and quick access to Dulles and Route 50/28.',
      housing: 'You will see everything from townhomes and colonials to larger newer homes in Loudoun-side communities.',
      schools: ['Good school options depending on zone', 'Strong youth sports and community activity', 'Balanced suburban feel'],
      commuteNotes: ['Direct access to Route 50 and 28', 'Solid Dulles and Fairfax commute profile', 'Useful for hybrid-work households'],
      highlights: ['Commuter practicality', 'Range of price points', 'Good Fairfax value pockets']
    },
    {
      slug: 'aldie',
      name: 'Aldie',
      county: 'Loudoun County',
      image: 'images/aldie.jpg',
      medianPrice: '$850K',
      schoolScore: '9/10',
      commute: '45 min',
      overview: 'Aldie gives buyers more space, newer communities, and a semi-rural backdrop without fully disconnecting from Northern Virginia job centers.',
      lifestyle: 'This is a favorite for buyers who want scenic neighborhoods, trails, and a more elevated suburban feel.',
      housing: 'Large single-family homes, estate-style lots, and upscale planned communities dominate the local housing mix.',
      schools: ['Strong Loudoun school reputation', 'Popular with move-up families', 'Community amenities often built around family routines'],
      commuteNotes: ['Longer commutes than inner suburbs', 'Best for buyers prioritizing space over shortest drive', 'Useful access via Route 50 and Loudoun County Parkway'],
      highlights: ['Scenic surroundings', 'Large newer homes', 'Luxury move-up market']
    },
    {
      slug: 'centreville',
      name: 'Centreville',
      county: 'Fairfax County',
      image: 'images/stoneridge.jpg',
      medianPrice: '$600K',
      schoolScore: '8/10',
      commute: '35 min',
      overview: 'Centreville remains one of the more practical ways into Fairfax County ownership for buyers who want access and livability without premium-core pricing.',
      lifestyle: 'It is suburban, connected, and full of familiar conveniences with strong access to I-66 and neighborhood retail.',
      housing: 'Townhomes, established single-family homes, and communities with mature landscaping give Centreville a lived-in feel.',
      schools: ['Well-known Fairfax County system', 'Popular for first move-up buyers', 'Solid extracurricular options'],
      commuteNotes: ['Strong I-66 access', 'Convenient for Fairfax and DC-bound commuters', 'Practical shopping and errands footprint'],
      highlights: ['Fairfax entry point', 'Commuter value', 'Established neighborhoods']
    },
    {
      slug: 'leesburg',
      name: 'Leesburg',
      county: 'Loudoun County',
      image: 'images/lansdowne.jpg',
      medianPrice: '$720K',
      schoolScore: '8/10',
      commute: '45 min',
      overview: 'Leesburg blends historic character with newer development, giving buyers more personality than a purely master-planned suburb.',
      lifestyle: 'Downtown restaurants, wineries, trails, and community events give the area a local identity buyers can feel.',
      housing: 'Historic homes, golf communities, and newer subdivisions all coexist here, which broadens the buyer pool.',
      schools: ['Strong Loudoun reputation', 'Mix of traditional and newer neighborhood zones', 'Good family draw'],
      commuteNotes: ['Longer commute, stronger lifestyle payoff', 'Good access to western Loudoun amenities', 'Appeals to buyers wanting more local character'],
      highlights: ['Historic downtown', 'Lifestyle-driven choice', 'Diverse housing stock']
    },
    {
      slug: 'south-riding',
      name: 'South Riding',
      county: 'Loudoun County',
      image: 'images/southriding.jpg',
      medianPrice: '$700K',
      schoolScore: '9/10',
      commute: '40 min',
      overview: 'South Riding is a perennial family favorite because it combines amenities, schools, and community identity better than many nearby options.',
      lifestyle: 'Pools, trails, neighborhood events, and a recognizable master-plan layout make this feel like a true live-and-stay community.',
      housing: 'Townhomes and detached homes dominate, with broad appeal for both first move-up and longer-term buyers.',
      schools: ['Strong Loudoun family draw', 'Neighborhood amenities tied to school-life rhythms', 'Very common buyer shortlist area'],
      commuteNotes: ['Good for Dulles corridor access', 'Not the shortest commute but a strong lifestyle trade', 'Easy comparison set against Ashburn and Aldie'],
      highlights: ['Master-planned amenities', 'Strong family demand', 'Reliable resale appeal']
    },
    {
      slug: 'brambleton',
      name: 'Brambleton',
      county: 'Loudoun County',
      image: 'images/brambleton.jpg',
      medianPrice: '$695K',
      schoolScore: '9/10',
      commute: '35 min',
      overview: 'Brambleton is one of Loudoun’s most recognizable planned communities, especially for buyers who want a polished, amenity-heavy neighborhood.',
      lifestyle: 'The town center, trails, pools, and built-in convenience appeal to buyers who want less sprawl in their daily routine.',
      housing: 'Townhomes, carriage homes, and detached properties give Brambleton range while keeping a cohesive neighborhood identity.',
      schools: ['Strong Loudoun appeal', 'Common target for relocating families', 'Modern community infrastructure'],
      commuteNotes: ['Good Loudoun commuter positioning', 'Convenient for tech corridor buyers', 'Often compared directly with Ashburn and Broadlands'],
      highlights: ['Town-center convenience', 'High-amenity living', 'Strong relocation appeal']
    },
    {
      slug: 'broadlands',
      name: 'Broadlands',
      county: 'Loudoun County',
      image: 'images/broadlands.jpg',
      medianPrice: '$710K',
      schoolScore: '9/10',
      commute: '35 min',
      overview: 'Broadlands offers mature landscaping, respected schools, and a stable community feel that appeals to buyers who want proven neighborhoods over novelty.',
      lifestyle: 'Residents value trails, golf access, pools, and a quieter tone than some of the busier mixed-use hubs nearby.',
      housing: 'Detached homes and townhomes in an established planned community create strong repeat demand.',
      schools: ['Reliable Loudoun school appeal', 'Well-known among move-up buyers', 'Strong neighborhood identity'],
      commuteNotes: ['Close to Ashburn conveniences', 'Good Route 7 and Greenway access', 'Popular for buyers balancing commute and calm'],
      highlights: ['Established community feel', 'Trails and golf access', 'Consistent resale demand']
    },
    {
      slug: 'one-loudoun',
      name: 'One Loudoun',
      county: 'Loudoun County',
      image: 'images/oneloudoun.jpg',
      medianPrice: '$820K',
      schoolScore: '8/10',
      commute: '30 min',
      overview: 'One Loudoun is the most urban-feeling option in this group, centered around walkable retail, restaurants, and entertainment.',
      lifestyle: 'It works best for buyers who want less driving for dining and social life while still staying in Loudoun.',
      housing: 'Townhomes, modern condos, and newer single-family options nearby create a more contemporary buyer profile.',
      schools: ['Appeals to buyers with mixed urban-suburban priorities', 'Access to Loudoun schools', 'Popular with professionals and younger families'],
      commuteNotes: ['Strong location for Dulles and Reston access', 'More central errand and dining convenience', 'Good hybrid-work fit'],
      highlights: ['Walkable mixed-use center', 'Modern housing stock', 'Lifestyle-first choice']
    }
  ]
};
